In [1]:
# Import pandas library
import pandas as pd

In [2]:
# Load excel file
df1 = pd.read_excel('file1.xlsx')
df1.head(2)

   OrderDate   Region     Rep    Item  Units  Unit Cost   Total
0 2019-01-06     East   Jones  Pencil     95       1.99  189.05
1 2019-01-23  Central  Kivell  Binder     50      19.99  999.50

In [3]:
# Load excel files
df2 = pd.read_excel('file2.xlsx')
df2.head(2)

   OrderDate   Region     Rep    Item  Units  Unit Cost   Total
0 2019-01-06     East   Jones  Pencil     95       1.99  189.05
1 2019-01-23  Central  Kivell  Binder     50      19.99  999.50

In [4]:
# merge both files using merge (similar concept like joins)

df_join = df1.merge(right = df2,
                    left_on = df1.columns.to_list(),
                    right_on = df2.columns.to_list(),
                    how = 'outer')

In [5]:
# By simply merging the fles we find that after files are merged, we are unable to differentiate the records
df_join

    OrderDate   Region       Rep     Item  Units  Unit Cost    Total
0  2019-01-06     East     Jones   Pencil     95       1.99   189.05
1  2019-01-23  Central    Kivell   Binder     50      19.99   999.50
2  2019-02-09  Central   Jardine   Pencil     36       4.99   179.64
3  2019-02-26  Central      Gill      Pen     27      19.99   539.73
4  2019-03-15     West   Sorvino   Pencil     56       2.99   267.44
5  2019-04-01     East     Jones   Binder     60       4.99   299.40
6  2019-04-18  Central   Andrews   Pencil     75       1.99   149.25
7  2019-05-05  Central   Jardine   Pencil     90       4.99   449.10
8  2019-05-22     West  Thompson   Binder     32       1.99    63.68
9  2019-06-08     East     Jones   Binder     60       8.99   539.40
10 2019-06-25  Central    Morgan   Pencil     90       4.99   449.10
11 2019-07-12     East      Gill   Binder     29       1.99    57.71
12 2019-07-29     East    Parent   Binder     81      19.99  1619.19
13 2019-08-15     East     Jones   Pencil     35       4.99   174.65
14 2019-09-01  Central     Smith     Desk      2     125.00   250.00
15 2019-09-18     East     Jones  Pen Set     16      15.99   255.84
16 2019-10-05  Central    Morgan   Binder     28       8.99   251.72
17 2019-10-22     East     Jones      Pen     64       8.99   575.36
18 2019-11-08     East    Parent      Pen     15      19.99   299.85
19 2019-11-25  Central    Kivell  Pen Set     96       4.99   479.04
20 2019-12-12  Central     Smith   Pencil     67       1.29    86.43
21 2019-12-29     East    Parent  Pen Set     74      15.99  1183.26
22 2020-01-15  Central      Gill   Binder     46       8.99   413.54
23 2020-02-01  Central     Smith   Binder     87      15.00  1305.00
24 2020-02-18     East     Jones   Binder      4       4.99    19.96
25 2020-03-07     West   Sorvino   Binder      7      19.99   139.93
26 2020-03-24  Central   Jardine  Pen Set     50       4.99   249.50
27 2020-04-10  Central   Andrews   Pencil     66       1.99   131.34
28 2020-04-27     East    Howard      Pen     96       4.99   479.04
29 2020-05-14  Central      Gill   Pencil     53       1.29    68.37
30 2020-05-31  Central      Gill   Binder     80       8.99   719.20
31 2020-06-17  Central    Kivell     Desk      5     125.00   625.00
32 2020-07-04     East     Jones  Pen Set     62       4.99   309.38
33 2020-07-21  Central    Morgan  Pen Set     55      12.49   686.95
34 2020-08-07  Central    Kivell  Pen Set     42      23.95  1005.90
35 2020-08-24     West   Sorvino     Desk      3     275.00   825.00
36 2020-09-10  Central      Gill   Pencil      7       1.29     9.03
37 2020-09-27     West   Sorvino      Pen     76       1.99   151.24
38 2020-10-14     West  Thompson   Binder     57      19.99  1139.43
39 2020-10-31  Central   Andrews   Pencil     14       1.29    18.06
40 2020-11-17  Central   Jardine   Binder     11       4.99    54.89
41 2020-12-04  Central   Jardine   Binder     94      19.99  1879.06
42 2020-12-21  Central   Andrews   Binder     28       4.99   139.72
43 2019-03-15     West   Sorvino   Pencil     56       2.99   167.44
44 2019-05-22     West  Thompson   Pencil     32       1.99    63.68
45 2019-07-12     East    Howard   Binder     29       1.99    57.71

In [6]:
# So we have to rename columns in both the files

df1.rename(columns = lambda x : x + '_file1', inplace=True)
df2.rename(columns = lambda x : x + '_file2', inplace=True)

In [7]:
# then perform merge functin again

df_join = df1.merge(right = df2,
                    left_on = df1.columns.to_list(),
                    right_on = df2.columns.to_list(),
                    how = 'outer')

In [8]:
# Now we can differentiate between records from both the files
df_join

,OrderDate_file1,Region_file1,Rep_file1,Item_file1,Units_file1,Unit Cost_file1,Total_file1,OrderDate_file2,Region_file2,Rep_file2,Item_file2,Units_file2,Unit Cost_file2,Total_file2
0,2019-01-06,East,Jones,Pencil,95.0,1.99,189.05,2019-01-06,East,Jones,Pencil,95.0,1.99,189.05
1,2019-01-23,Central,Kivell,Binder,50.0,19.99,999.50,2019-01-23,Central,Kivell,Binder,50.0,19.99,999.50
2,2019-02-09,Central,Jardine,Pencil,36.0,4.99,179.64,2019-02-09,Central,Jardine,Pencil,36.0,4.99,179.64
3,2019-02-26,Central,Gill,Pen,27.0,19.99,539.73,2019-02-26,Central,Gill,Pen,27.0,19.99,539.73
4,2019-03-15,West,Sorvino,Pencil,56.0,2.99,267.44,NaT,NaN,NaN,NaN,NaN,NaN,NaN
5,2019-04-01,East,Jones,Binder,60.0,4.99,299.40,2019-04-01,East,Jones,Binder,60.0,4.99,299.40
6,2019-04-18,Central,Andrews,Pencil,75.0,1.99,149.25,2019-04-18,Central,Andrews,Pencil,75.0,1.99,149.25
7,2019-05-05,Central,Jardine,Pencil,90.0,4.99,449.10,2019-05-05,Central,Jardine,Pencil,90.0,4.99,449.10
8,2019-05-22,West,Thompson,Binder,32.0,1.99,63.68,NaT,NaN,NaN,NaN,NaN,NaN,NaN
9,2019-06-08,East,Jones,Binder,60.0,8.99,539.40,2019-06-08,East,Jones,Binder,60.0,8.99,539.40
10,2019-06-25,Central,Morgan,Pencil,90.0,4.99,449.10,2019-06-25,Central,Morgan,Pencil,90.0,4.99,449.10
11,2019-07-12,East,Gill,Binder,29.0,1.99,57.71,NaT,NaN,NaN,NaN,NaN,NaN,NaN
12,2019-07-29,East,Parent,Binder,81.0,19.99,1619.19,2019-07-29,East,Parent,Binder,81.0,19.99,1619.19
13,2019-08-15,East,Jones,Pencil,35.0,4.99,174.65,2019-08-15,East,Jones,Pencil,35.0,4.99,174.65
14,2019-09-01,Central,Smith,Desk,2.0,125.00,250.00,2019-09-01,Central,Smith,Desk,2.0,125.00,250.00
15,2019-09-18,East,Jones,Pen Set,16.0,15.99,255.84,2019-09-18,East,Jones,Pen Set,16.0,15.99,255.84
16,2019-10-05,Central,Morgan,Binder,28.0,8.99,251.72,2019-10-05,Central,Morgan,Binder,28.0,8.99,251.72
17,2019-10-22,East,Jones,Pen,64.0,8.99,575.36,2019-10-22,East,Jones,Pen,64.0,8.99,575.36
18,2019-11-08,East,Parent,Pen,15.0,19.99,299.85,2019-11-08,East,Parent,Pen,15.0,19.99,299.85
19,2019-11-25,Central,Kivell,Pen Set,96.0,4.99,479.04,2019-11-25,Central,Kivell,Pen Set,96.0,4.99,479.04
20,2019-12-12,Central,Smith,Pencil,67.0,1.29,86.43,2019-12-12,Central,Smith,Pencil,67.0,1.29,86.43
21,2019-12-29,East,Parent,Pen Set,74.0,15.99,1183.26,2019-12-29,East,Parent,Pen Set,74.0,15.99,1183.26
22,2020-01-15,Central,Gill,Binder,46.0,8.99,413.54,NaT,NaN,NaN,NaN,NaN,NaN,NaN
23,2020-02-01,Central,Smith,Binder,87.0,15.00,1305.00,2020-02-01,Central,Smith,Binder,87.0,15.00,1305.00
24,2020-02-18,East,Jones,Binder,4.0,4.99,19.96,2020-02-18,East,Jones,Binder,4.0,4.99,19.96
25,2020-03-07,West,Sorvino,Binder,7.0,19.99,139.93,2020-03-07,West,Sorvino,Binder,7.0,19.99,139.93
26,2020-03-24,Central,Jardine,Pen Set,50.0,4.99,249.50,2020-03-24,Central,Jardine,Pen Set,50.0,4.99,249.50
27,2020-04-10,Central,Andrews,Pencil,66.0,1.99,131.34,2020-04-10,Central,Andrews,Pencil,66.0,1.99,131.34
28,2020-04-27,East,Howard,Pen,96.0,4.99,479.04,2020-04-27,East,Howard,Pen,96.0,4.99,479.04
29,2020-05-14,Central,Gill,Pencil,53.0,1.29,68.37,2020-05-14,Central,Gill,Pencil,53.0,1.29,68.37
30,2020-05-31,Central,Gill,Binder,80.0,8.99,719.20,2020-05-31,Central,Gill,Binder,80.0,8.99,719.20
31,2020-06-17,Central,Kivell,Desk,5.0,125.00,625.00,NaT,NaN,NaN,NaN,NaN,NaN,NaN
32,2020-07-04,East,Jones,Pen Set,62.0,4.99,309.38,2020-07-04,East,Jones,Pen Set,62.0,4.99,309.38
33,2020-07-21,Central,Morgan,Pen Set,55.0,12.49,686.95,2020-07-21,Central,Morgan,Pen Set,55.0,12.49,686.95
34,2020-08-07,Central,Kivell,Pen Set,42.0,23.95,1005.90,2020-08-07,Central,Kivell,Pen Set,42.0,23.95,1005.90
35,2020-08-24,West,Sorvino,Desk,3.0,275.00,825.00,2020-08-24,West,Sorvino,Desk,3.0,275.00,825.00
36,2020-09-10,Central,Gill,Pencil,7.0,1.29,9.03,2020-09-10,Central,Gill,Pencil,7.0,1.29,9.03
37,2020-09-27,West,Sorvino,Pen,76.0,1.99,151.24,2020-09-27,West,Sorvino,Pen,76.0,1.99,151.24
38,2020-10-14,West,Thompson,Binder,57.0,19.99,1139.43,2020-10-14,West,Thompson,Binder,57.0,19.99,1139.43
39,2020-10-31,Central,Andrews,Pencil,14.0,1.29,18.06,2020-10-31,Central,Andrews,Pencil,14.0,1.29,18.06
40,2020-11-17,Central,Jardine,Binder,11.0,4.99,54.89,2020-11-17,Central,Jardine,Binder,11.0,4.99,54.89
41,2020-12-04,Central,Jardine,Binder,94.0,19.99,1879.06,2020-12-04,Central,Jardine,Binder,94.0,19.99,1879.06
42,2020-12-21,Central,Andrews,Binder,28.0,4.99,139.72,2020-12-21,Central,Andrews,Binder,28.0,4.99,139.72
43,NaT,NaN,NaN,NaN,NaN,NaN,NaN,2019-03-15,West,Sorvino,Pencil,56.0,2.99,167.44
44,NaT,NaN,NaN,NaN,NaN,NaN,NaN,2019-05-22,West,Thompson,Pencil,32.0,1.99,63.68
45,NaT,NaN,NaN,NaN,NaN,NaN,NaN,2019-07-12,East,Howard,Binder,29.0,1.99,57.71

In [9]:
# to get records_present_in_df1_not_in_df2:-

records_present_in_df1_not_in_df2 = df_join.loc[df_join[df2.columns.to_list()].isnull().all(axis = 1), df1.columns.to_list()]

In [10]:
records_present_in_df1_not_in_df2

,OrderDate_file1,Region_file1,Rep_file1,Item_file1,Units_file1,Unit Cost_file1,Total_file1
4,2019-03-15,West,Sorvino,Pencil,56.0,2.99,267.44
8,2019-05-22,West,Thompson,Binder,32.0,1.99,63.68
11,2019-07-12,East,Gill,Binder,29.0,1.99,57.71
22,2020-01-15,Central,Gill,Binder,46.0,8.99,413.54
31,2020-06-17,Central,Kivell,Desk,5.0,125.00,625.00

In [11]:
# to get records_present_in_df2_not_in_df1:-

records_present_in_df2_not_in_df1 = df_join.loc[df_join[df1.columns.to_list()].isnull().all(axis = 1), df2.columns.to_list()]

In [12]:
records_present_in_df2_not_in_df1

,OrderDate_file2,Region_file2,Rep_file2,Item_file2,Units_file2,Unit Cost_file2,Total_file2
43,2019-03-15,West,Sorvino,Pencil,56.0,2.99,167.44
44,2019-05-22,West,Thompson,Pencil,32.0,1.99,63.68
45,2019-07-12,East,Howard,Binder,29.0,1.99,57.71

In [13]:
# This is how we can compare 2 files using python pandas library.

In [14]:
record_1 = records_present_in_df1_not_in_df2
record_2 = records_present_in_df2_not_in_df1

In [15]:
df_new_join = record_1.merge(right=record_2,
                            left_on=record_1.columns.to_list(),
                            right_on=record_2.columns.to_list(),
                            how = "outer")

In [16]:
df_new_join

,OrderDate_file1,Region_file1,Rep_file1,Item_file1,Units_file1,Unit Cost_file1,Total_file1,OrderDate_file2,Region_file2,Rep_file2,Item_file2,Units_file2,Unit Cost_file2,Total_file2
0,2019-03-15,West,Sorvino,Pencil,56.0,2.99,267.44,NaT,NaN,NaN,NaN,NaN,NaN,NaN
1,2019-05-22,West,Thompson,Binder,32.0,1.99,63.68,NaT,NaN,NaN,NaN,NaN,NaN,NaN
2,2019-07-12,East,Gill,Binder,29.0,1.99,57.71,NaT,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-01-15,Central,Gill,Binder,46.0,8.99,413.54,NaT,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-06-17,Central,Kivell,Desk,5.0,125.00,625.00,NaT,NaN,NaN,NaN,NaN,NaN,NaN
5,NaT,NaN,NaN,NaN,NaN,NaN,NaN,2019-03-15,West,Sorvino,Pencil,56.0,2.99,167.44
6,NaT,NaN,NaN,NaN,NaN,NaN,NaN,2019-05-22,West,Thompson,Pencil,32.0,1.99,63.68
7,NaT,NaN,NaN,NaN,NaN,NaN,NaN,2019-07-12,East,Howard,Binder,29.0,1.99,57.71

In [20]:
df_new_join.to_excel('output.xlsx')